import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Darksideuy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="relative min-h-full flex flex-col bg-black overflow-x-hidden">

        {/* ================= BACKGROUND LAYERS ================= */}
        <div className="fixed inset-0 z-0 overflow-hidden">

          {/* IMAGE LAYER (con zoom + parallax suave) */}
          <div className="absolute inset-0 scale-110 animate-slow-zoom">
            <Image
              src="/background-image.jpeg"
              alt="Background"
              fill
              priority
              className="object-cover opacity-30"
            />
          </div>

          {/* GRADIENT DEPTH LAYER */}
          <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/40 to-black/85" />

          {/* NOISE / GRAIN LAYER (da textura cinematográfica) */}
          <div className="absolute inset-0 opacity-[0.08] mix-blend-overlay noise-texture" />

        </div>

        {/* CONTENIDO */}
        <div className="relative z-10">
          {children}
        </div>

      </body>
    </html>
  );
}